server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    # Afficher la page de statut aussi en HTTP.
    location / {
        try_files $uri $uri/ /index.html /index.nginx-debian.html =404;
    }
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;
    server_name _;

    # Certificat local par défaut (navigateur affichera "non sécurisé" sur IP)
    ssl_certificate /etc/ssl/certs/ssl-cert-snakeoil.pem;
    ssl_certificate_key /etc/ssl/private/ssl-cert-snakeoil.key;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    # Afficher la page de statut aussi en HTTPS.
    location / {
        try_files $uri $uri/ /index.html /index.nginx-debian.html =404;
    }
}
