#!/usr/bin/env sh

LOG_FILE=".husky/logs/husky-pre-auto-gc.$(date '+%Y-%m-%d').log"
mkdir -p .husky/logs

. "$(dirname "$0")/scripts/committag.sh"
get_commit_and_tag

{
	echo "------------------------------"
	echo "$(date '+%Y-%m-%d %H:%M:%S')"
	echo "Hook        : pre-auto-gc"
	echo "User        : $(git config user.name) <$(git config user.email)>"
	echo "Last commit : $COMMIT_MSG"
	echo "Cur. branch : $CURRENT_BRANCH"
	echo "Last tag    : $LAST_TAG"
	echo "------------------------------"
} >>"$LOG_FILE"

echo "END pre-auto-gc" >>"$LOG_FILE"
